### ISSUE TITLE
export yolov8-pose model tflite int8

### ISSUE THREAD

**Issue by jbdebelle** [DeGirum/PySDKExamples#46]
Description:
I encountered an error while attempting to convert the pose model yolov8n-pose.pt to TensorFlow Lite (TFLite) int8 format. Below are the steps I followed:

Ran `python dg_export.py --weights yolov8n-pose.pt --quantize --data coco8-pose.yaml` to export the model with quantization.

Ran `python dg_predict.py --weights ./yolov8n-pose_saved_model/yolov8n-pose_full_integer_quant.tflite --source ./ultralytics/assets/bus.jpg --device cpu` for prediction.

However, I received the following error during the prediction step:

`RuntimeError: Trying to create tensor with negative dimension -941: [0, -941]`

It seems like there is an issue with negative dimensions during tensor creation. I've tried troubleshooting it, but haven't been successful in resolving it.

Has anyone else encountered a similar error? Any assistance or insights from the Degirum community would be greatly appreciated.

Thank you.

**Comment by shashichilappagari** [comment]
@jbdebelle Thanks for reporting this. @khatami-mehrdad  and @franklin-degirum can you please take a look?

**Comment by khatami-mehrdad** [comment]
@jbdebelle Thank you for bringing this to our attention. 
We know the reason why this happens. We will fix it ASAP.

**Comment by khatami-mehrdad** [comment]
@jbdebelle The issue is resolved in the latest master. 
Thank you for your feedback.

**Comment by khatami-mehrdad** [comment]
Resolved.

**Comment by jbdebelle** [comment]
Hello I still get an error. 
``File "/venv/lib/python3.10/site-packages/tensorflow/lite/python/optimize/calibrator.py", line 152, in _feed_tensors
    self._calibrator.FeedTensor(input_array)
ValueError: Cannot set tensor: Got value of type FLOAT64 but expected type FLOAT32 for input 0, name: serving_default_images:0 ``
Now i tried to convert the images in the folder to float32 and I still get the same error plus a warning  :
`ignoring corrupt image/label: cannot reshape array of size 55 into shape (2)`

Let me know if you have any insights on how to fix this

**Comment by khatami-mehrdad** [comment]
@jbdebelle 
The error you are facing is due to onnx2tf version 1.17.5.
I made a change it our repository which will make sure you have the correct version (onnx2tf>=1.19.12) now.
Please pull [ultralytics_yolov8](https://github.com/DeGirum/ultralytics_yolov8) again and run the same cmd.
It checks and updates onnx2tf to the correct version.
Please let me know if this resolves the issue.
